scalar Date

type Query {
  ping: String
  libraries: [Library]!
  library(id: ID!, page: Int = 1, pageSize: Int = 50): LibraryDetail
  book(id: ID!): Book
  searchBooks(searchQuery: SearchBooksQuery!): PaginatedBooksList!
  contacts: [Contact]!
  contact(id: ID!): Contact
  lendings(page: Int! = 1): PaginatedLendingsList!
}

type Mutation {
  addLibrary(library: LibraryInput!): Library!
  updateLibrary(library: LibraryInput!): Boolean
  removeLibrary(id: ID!): Boolean
  addBook(book: BookInput!): Book!
  updateBook(book: BookInput!): Boolean
  removeBook(id: ID!): Boolean
  addContact(contact: ContactInput!): Contact!
  updateContact(contact: ContactInput!): Boolean
  removeContact(id: ID!): Boolean
  resizeImage(image: Image!): String
}

input Image {
  width: Int!
  height: Int!
  image: String @constraint(format: "byte")
  imageUrl: String @constraint(format: "uri")
}

input SearchBooksQuery {
  page: Int = 1 @constraint(min: 1)
  pageSize: Int = 50 @constraint(min: 1, max: 50)
  keywords: [String!]!
}

type PaginatedBooksList {
  total: Int!
  itemsPerPage: Int!
  books: [Book]!
}

type Library {
  id: ID!
  name: String!
  description: String
  booksCount: Int!
}

input LibraryInput {
  id: ID
  name: String!
  description: String
}

type LibraryDetail {
  id: ID!
  name: String!
  description: String
  content: PaginatedBooksList
}

input BookInput {
  id: ID
  title: String!
  description: String = ""
  isbn10: String = ""
  isbn13: String = ""
  thumbnail: String = ""
  authors: [String] = []
  tags: [String] = []
  bookSet: String = ""
  bookSetOrder: Int = 0
  language: String = "fr"
  libraryId: ID
}

type Book {
  id: ID!
  title: String!
  description: String
  isbn10: String
  isbn13: String
  thumbnail: String
  authors: [String]
  tags: [String]
  bookSet: String
  bookSetOrder: Int
  language: String
  lendingId: ID
  library: Library!
}

type Contact {
  id: ID!
  nickname: String!
  thumbnail: String
}

input ContactInput {
  id: ID
  nickname: String!
  thumbnail: String
}

type PaginatedLendingsList {
  total: Int!
  itemsPerPage: Int!
  lendings: [Lending]!
}

type Lending {
  id: ID!
  bookId: ID!
  bookTitle: String!
  borrowerId: ID!
  borrowerNickname: String!
  status: String!
  lentAt: Date!
  returnedAt: Date
}
